### ISSUE TITLE
Issue when installing compiledcode

### ISSUE THREAD

**Issue by JonoYang** [nexB/scancode-plugins#15]
I get the following error when I install `binary-analysis/scancode-compiledcode/`.

```
(scancode-toolkit) jono@mingus:~/nexb/src/scancode-plugins/binary-analysis
$ scancode -h
========================================================================
ERROR: UNABLE TO IMPORT SCANCODE PLUGINS.
Check your installation configuration (setup.py) or re-install/re-configure ScanCode.
The following plugin(s) are referenced and cannot be loaded/imported:
No module named 'sourcecode'
========================================================================
Traceback (most recent call last):
  File "/home/jono/nexb/src/scancode-toolkit/bin/scancode", line 33, in <module>
    sys.exit(load_entry_point('scancode-toolkit', 'console_scripts', 'scancode')())
  File "/home/jono/nexb/src/scancode-toolkit/bin/scancode", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/jono/nexb/src/scancode-toolkit/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/jono/nexb/src/scancode-toolkit/src/scancode/cli.py", line 122, in <module>
    raise e
  File "/home/jono/nexb/src/scancode-toolkit/src/scancode/cli.py", line 109, in <module>
    plugin_classes, plugin_options = PluginManager.load_plugins()
  File "/home/jono/nexb/src/scancode-toolkit/lib/python3.6/site-packages/plugincode/__init__.py", line 207, in load_plugins
    mgr_setup = manager.setup()
  File "/home/jono/nexb/src/scancode-toolkit/lib/python3.6/site-packages/plugincode/__init__.py", line 233, in setup
    raise e
  File "/home/jono/nexb/src/scancode-toolkit/lib/python3.6/site-packages/plugincode/__init__.py", line 231, in setup
    self.manager.load_setuptools_entrypoints(entrypoint)
  File "/home/jono/nexb/src/scancode-toolkit/lib/python3.6/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/home/jono/nexb/src/scancode-toolkit/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 167, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'sourcecode'
```

**Comment by kamalishere** [comment]
hi i would like to work on this.

**Comment by pombredanne** [comment]
@kamalishere Thanks! have you been able to reproduce this?

**Comment by kamalishere** [comment]
@pombredanne no actually, please guide me a bit. I am new here.

**Comment by pombredanne** [comment]
You need to 1. install scancode-toolkit and 2.checkout and install the compiledcode plugin in it with pip.

**Comment by kamalishere** [comment]
ok i am working on it
